#!/usr/bin/perl
## Wang Dianhui, GUET
## Sep. 13, 2015

die "\$(scriptName) nStart nEnd [atomName]\n" until $ARGV[1];
$nStart = $ARGV[0];
$nEnd = $ARGV[1];
if ($ARGV[2]){
   $name = $ARGV[2];
}else{
   $name = summed;
}

for $n($nStart..$nEnd){
   $fileName = sprintf("iLDOS%03d",$n);
   open INPUT, "< $fileName";
   print "Processing data $fileName ...\n";
   $nEDOS = 0;
   while (<INPUT>){
      @tmpDOS = split ' ', $_;
      $DOS[$nEDOS][0] = $tmpDOS[0];
      for $i(1..$#tmpDOS){
         $DOS[$nEDOS][$i] += $tmpDOS[$i];
      }
      $nEDOS++;
   }
   close INPUT;
}


open OUT, "> dosp.$name.dat";
for $i(0..$nEDOS-1){
   for $j(0..$#tmpDOS){
      printf OUT (" %11.6f",$DOS[$i][$j]);
   }
   print OUT "\n";
}
close OUT;
      
print "Summed DOS has been written to file \"dosp.$name.dat\".\n";
